version: '3.8'

services:
  api:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=healthcare;Username=postgres;Password=postgres
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=healthcare
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  orthanc:
    image: jodogne/orthanc-plugins
    ports:
      - "4242:4242"
      - "8042:8042"
    volumes:
      - orthanc_data:/var/lib/orthanc/db
    environment:
      - ORTHANC__NAME=HealthcareOrthanc
      - ORTHANC__DICOM_SERVER_ENABLED=true
      - ORTHANC__DICOM_MODALITIES={"sample":["SAMPLE","127.0.0.1",104]}

volumes:
  postgres_data:
  orthanc_data:
